GET http://localhost:8000/nutrition_app/v1/food/list

###

POST http://localhost:8000/nutrition_app/v1/auth/register
content-type: application/json

{
    "username": "alok",
    "email": "alokkumar23242@gmail.com",
    "password": "applemango123"
}

###

POST http://localhost:8000/nutrition_app/v1/auth/login
content-type: application/json

{
    "email": "apple.mango@gmail.com",
    "password": "applemango123"
}

###

POST http://localhost:8000/nutrition_app/v1/foodlist/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmExNDNiZDlkMTcyMTM1YmQ5NDc4YmUiLCJpYXQiOjE3MjIyODE1MjYsImV4cCI6MTcyMjI4MjQyNn0.qhL4YfQJsek-r94H8I8hWB9suLF2B3qQQ9J6tuARNTM
content-type: application/json

{
    "foodId": 2341752
}