POST http://localhost:8000/nutrition_app/v1/auth/register
content-type: application/json

{
    "username": "alok",
    "email": "alokkumar23242@gmail.com",
    "password": "applemango123"
}

###

POST http://localhost:8000/nutrition_app/v1/auth/login
content-type: application/json

{
    "email": "apple.mango@gmail.com",
    "password": "applemango123"
}

###

POST http://localhost:8000/nutrition_app/v1/foodlist/add
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmExNDNiZDlkMTcyMTM1YmQ5NDc4YmUiLCJpYXQiOjE3MjE5MDAwODV9.rJhJnyx9gR_gajceqFIOcsKdMG81qMMsUbzxOqzkP4I

{
}